/* Data generator: Wikipedia "List of airports in Australia" wikitext -> airports-data.js
 *
 * To regenerate:
 *   1. Fetch the source wikitext:
 *      curl.exe -s "https://en.wikipedia.org/w/index.php?title=List_of_airports_in_Australia&action=raw" -o aus_airports_raw.txt
 *   2. node parse_airports.js
 *
 * Reads aus_airports_raw.txt, writes airports-data.js.
 */
const fs = require("fs");

const raw = fs.readFileSync("aus_airports_raw.txt", "utf8");
const lines = raw.split(/\r?\n/);

// Section header -> { region, type }. Military sections are grouped & tagged.
function classify(header) {
  if (/^Military:/i.test(header)) {
    return { region: "Australia (Military)", type: "Military airbase" };
  }
  return { region: header, type: "Airport" };
}

function cleanText(s) {
  if (s == null) return "";
  let t = s;
  t = t.replace(/<!--[\s\S]*?-->/g, "");               // html comments
  t = t.replace(/<ref[^>]*\/>/gi, "");                 // self-closing refs
  t = t.replace(/<ref[^>]*>[\s\S]*?<\/ref>/gi, "");    // paired refs
  t = t.replace(/\{\{\s*small\s*\|([^{}]*)\}\}/gi, "$1"); // {{small|x}} -> x
  t = t.replace(/\{\{[^{}]*\}\}/g, "");                // drop any other templates
  t = t.replace(/<\/?s>/gi, "");                       // strikethrough (closed) tags
  t = t.replace(/\[\[[^\]|]*\|([^\]]*)\]\]/g, "$1");   // [[target|display]] -> display
  t = t.replace(/\[\[([^\]]*)\]\]/g, "$1");            // [[page]] -> page
  t = t.replace(/'''/g, "").replace(/''/g, "");        // bold/italics
  t = t.replace(/&nbsp;/g, " ");
  t = t.replace(/<br\s*\/?>/gi, ", ");
  t = t.replace(/\s+/g, " ").trim();
  return t;
}

function extractIcao(cell) {
  const m = cell.match(/\{\{\s*AIP[ _]AU\s*\|\s*([^}|]+?)\s*\}\}/i);
  if (m) return m[1].trim();
  return cleanText(cell);
}

let currentSection = null;
let inTable = false;
let cells = [];        // accumulated cells for the current row
const airports = [];

function flushRow() {
  if (!currentSection || cells.length < 4) {
    cells = [];
    return;
  }
  // Expected column order: City | ICAO | IATA | Airport name
  const rawCity = cells[0];
  const icao = extractIcao(cells[1]);
  const iata = cleanText(cells[2]);
  const rawName = cells[3];

  const city = cleanText(rawCity);
  const name = cleanText(rawName);
  const scheduled = /'''/.test(rawName);      // bold name = scheduled passenger service
  const international = /'''/.test(rawCity);   // bold city = international

  // Skip header rows / empties
  if (!name || /city served/i.test(city)) {
    cells = [];
    return;
  }

  const { region, type } = classify(currentSection);
  airports.push({
    code: icao,
    iata: iata,
    name: name,
    city: city,
    country: "Australia",
    region: region,
    type: type,
    scheduled: scheduled,
    international: international,
  });
  cells = [];
}

for (let i = 0; i < lines.length; i++) {
  const line = lines[i];

  const sec = line.match(/^===\s*(.*?)\s*===\s*$/);
  if (sec) {
    flushRow();
    currentSection = sec[1];
    inTable = false;
    continue;
  }

  if (/^\{\|/.test(line)) { inTable = true; cells = []; continue; }
  if (!inTable) continue;

  if (/^\|\}/.test(line)) { flushRow(); inTable = false; continue; }

  if (/^\|-/.test(line)) { flushRow(); continue; } // new row boundary
  if (/^!/.test(line)) { continue; }               // header cells -> ignore

  if (/^\|/.test(line)) {
    // A data cell line. Strip leading pipe(s). Handle "|| a || b" on one line too.
    const body = line.replace(/^\|+/, "");
    const parts = body.split(/\|\|/);
    for (const p of parts) cells.push(p.trim());
    continue;
  }
}
flushRow();

// De-dupe by ICAO+name (defensive)
const seen = new Set();
const deduped = airports.filter((a) => {
  const k = a.code + "|" + a.name;
  if (seen.has(k)) return false;
  seen.add(k);
  return true;
});

// Report
const byRegion = {};
for (const a of deduped) byRegion[a.region] = (byRegion[a.region] || 0) + 1;
console.log("Total airports:", deduped.length);
console.log("By region:", JSON.stringify(byRegion, null, 2));
console.log("Sample:", JSON.stringify(deduped.slice(0, 3), null, 2));
const noIcao = deduped.filter((a) => !a.code).length;
console.log("Rows missing ICAO:", noIcao);

// Emit airports-data.js (augments window.PORTS so seaports + airports coexist)
const header = `/* Australian airports — generated from Wikipedia "List of airports in Australia".
 * Source: https://en.wikipedia.org/wiki/List_of_airports_in_Australia
 * Generated by parse_airports.js. Do not edit by hand; re-run the parser.
 *
 * Each entry: { code (ICAO), iata, name, city, country, region, type, scheduled, international }
 * Appended to window.PORTS so the existing search UI works unchanged.
 */
window.PORTS = (window.PORTS || []).concat([\n`;

const rows = deduped
  .map((a) => "  " + JSON.stringify(a) + ",")
  .join("\n");

const footer = "\n]);\n";

fs.writeFileSync("airports-data.js", header + rows + footer, "utf8");
console.log("Wrote airports-data.js");
